### PR TITLE
Add label filtering function

### PR DESCRIPTION
**Pull request by StRigaud**
adding:

- `filter_label_by_size` (t4)
- `remove_small_objects` (t5)
- `remove_big_objects` (t5)
- `remove_holes` (t6)

they are equivalent and derivation to the prototype functions

- `exclude_labels_outside_size_range`
- `exclude_small_labels`

Also rename function for consistancy

`exclude_labels` -> `remove_labels`

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
I'm not overly excited about the new names: "remove_big_objects" was called "exclude_large_labels" in pyclesperanto_prototype. I'm wondering why these renamings are necessary. The community might not appreciate this.

**Comment by StRigaud** [comment]
@haesleinhuepf Is this really an issue or not? To know if I can release this or set it back to `_prototype` naming?

**Comment by haesleinhuepf** [comment]
Well if you want to make it easy for prototype users to switch to pyclesperanto, I suggest to keep the API whereever possible. If your target audience are scikit-image folks, I would suggest to make the API similar to scikit-image. The second option seems a lot of work to me.

**Comment by StRigaud** [comment]
I won't mimic scikit-image API no, not sure if possible anyway. But keep some convention names can help users. TBH i am more used to `remove` than to `exclude` in my head. This can hinder users when searching for a operation name. 

I can have both cohexist also and we can add a `deprecated` later on.

**Comment by haesleinhuepf** [comment]
Yeah, let's sync names a bit. For example let's not introduce "objects" in some function names where we mean "labels". Also lets keep "large" instead of "big". This should be consistent with pyclesperanto an scikit image

**Comment by thawn** [comment]
maybe I can add the perspective of a user who recently switched to pyclesperanto from the _prototype:

First of all, I think pyclesperanto already works very well and I am using it in more and more projects - so big thanks!

For me it was very convenient to be able to just replace `import pyclesperanto_prototype as cle` with `import pyclesperanto as cle` If that had not been possible, I would not have switched.

Then some deprecation messages started to pop up, which I found annoying. This is increasing the hurdle to switch from the prototype to pyclesperanto.  Adding aliases and new functions is fine, but deprecation messages and renamed functions are a real show-stopper for me. I am using the code to support collaboration partners. If my notebooks and log files are full of deprecation messages, this does not look professional.

(admittedly not completely without self-interest) I suggest to first focus on the user base which is most likely to switch to pyclesperanto. In my opinion, that are _prototype users (because of the plug-in replacement effect). The more users you have, the better your code will become (through bug reports and feature requests).

Once pyclesperanto is a complete replacement for the prototype, it would be ideal to introduce a deprecation notice in the prototype to trigger everyone to switch. However, IMHO this is only possible, if pyclesperanto is still a plug-in replacement at that time.

Until then, I would keep the pyclesperanto API 100% compatible to the prototype if possible.

**Comment by StRigaud** [comment]
Thanks @thawn, very helpfull :)

I did a quick check on my side, asking people, and `remove` is clearly the most intuitive and preferable. So I will make this kind of equivalent function co-exists for now.  I will try to fit as much to the `_prototype` before introducting API change though there will be some minimal adaptation as I cannot perfectly replicate all.

I understand the annoyance of the warning (btw I think you can silence them in Python). But I guess it can also be possible to simply remove the warning for now, focus on aliases and multi-naming, and then start adding warning later once the shift is fully done.

**Comment by thawn** [comment]
@StRigaud sounds great, thanks a lot!

**Pull request merged**
